# Generated by Django 5.0.7 on 2024-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("mobile", models.TextField()),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
