# Generated by Django 5.0.7 on 2024-07-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proj1app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="Employee",
        ),
    ]
